// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhongKham.Data;

#nullable disable

namespace QuanLyPhongKham.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhongKham.Models.BuoiKham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacSiId")
                        .HasColumnType("int");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Gio")
                        .HasColumnType("time");

                    b.Property<int?>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int?>("KetQuaKhamId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<int>("PhongKhamId")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("PhongKhamId");

                    b.ToTable("BuoiKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.ChuyenKhoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChuyenKhoas");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.HoaDon", b =>
                {
                    b.Property<int>("BuoiKhamId")
                        .HasColumnType("int");

                    b.HasKey("BuoiKhamId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.KetQuaKham", b =>
                {
                    b.Property<int>("BuoiKhamId")
                        .HasColumnType("int");

                    b.Property<string>("KetQua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuoiKhamId");

                    b.ToTable("KetQuaKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.PhongKham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiPhong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoPhong")
                        .HasColumnType("int");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhongKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhauHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.TieuSuBenhAn", b =>
                {
                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenhNhanId");

                    b.ToTable("TieuSuBenhAns");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Admin", b =>
                {
                    b.HasBaseType("QuanLyPhongKham.Models.NguoiDung");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.BacSi", b =>
                {
                    b.HasBaseType("QuanLyPhongKham.Models.NguoiDung");

                    b.Property<int?>("ChuyenKhoaId")
                        .HasColumnType("int");

                    b.Property<int?>("PhongLamViecId")
                        .HasColumnType("int");

                    b.HasIndex("ChuyenKhoaId");

                    b.HasIndex("PhongLamViecId")
                        .IsUnique()
                        .HasFilter("[PhongLamViecId] IS NOT NULL");

                    b.ToTable("BacSis", (string)null);
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.BenhNhan", b =>
                {
                    b.HasBaseType("QuanLyPhongKham.Models.NguoiDung");

                    b.ToTable("BenhNhans", (string)null);
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.LeTan", b =>
                {
                    b.HasBaseType("QuanLyPhongKham.Models.NguoiDung");

                    b.ToTable("LeTans", (string)null);
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.BuoiKham", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.BacSi", "BacSi")
                        .WithMany("BuoiKhams")
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhongKham.Models.BenhNhan", "BenhNhan")
                        .WithMany("BuoiKhams")
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyPhongKham.Models.PhongKham", "PhongKham")
                        .WithMany("BuoiKhams")
                        .HasForeignKey("PhongKhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");

                    b.Navigation("PhongKham");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.BuoiKham", "BuoiKham")
                        .WithOne("HoaDon")
                        .HasForeignKey("QuanLyPhongKham.Models.HoaDon", "BuoiKhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuoiKham");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.KetQuaKham", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.BuoiKham", "BuoiKham")
                        .WithOne("KetQuaKham")
                        .HasForeignKey("QuanLyPhongKham.Models.KetQuaKham", "BuoiKhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuoiKham");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.NguoiDung", "NguoiDung")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyPhongKham.Models.TaiKhoan", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.TieuSuBenhAn", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.BenhNhan", "BenhNhan")
                        .WithOne("TieuSuBenhAn")
                        .HasForeignKey("QuanLyPhongKham.Models.TieuSuBenhAn", "BenhNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.Admin", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.NguoiDung", null)
                        .WithOne()
                        .HasForeignKey("QuanLyPhongKham.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.BacSi", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("BacSis")
                        .HasForeignKey("ChuyenKhoaId");

                    b.HasOne("QuanLyPhongKham.Models.NguoiDung", null)
                        .WithOne()
                        .HasForeignKey("QuanLyPhongKham.Models.BacSi", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhongKham.Models.PhongKham", "PhongLamViec")
                        .WithOne("BacSi")
                        .HasForeignKey("QuanLyPhongKham.Models.BacSi", "PhongLamViecId");

                    b.Navigation("ChuyenKhoa");

                    b.Navigation("PhongLamViec");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.BenhNhan", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.NguoiDung", null)
                        .WithOne()
                        .HasForeignKey("QuanLyPhongKham.Models.BenhNhan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.LeTan", b =>
                {
                    b.HasOne("QuanLyPhongKham.Models.NguoiDung", null)
                        .WithOne()
                        .HasForeignKey("QuanLyPhongKham.Models.LeTan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.BuoiKham", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("KetQuaKham");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.ChuyenKhoa", b =>
                {
                    b.Navigation("BacSis");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.NguoiDung", b =>
                {
                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.PhongKham", b =>
                {
                    b.Navigation("BacSi");

                    b.Navigation("BuoiKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.BacSi", b =>
                {
                    b.Navigation("BuoiKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham.Models.BenhNhan", b =>
                {
                    b.Navigation("BuoiKhams");

                    b.Navigation("TieuSuBenhAn");
                });
#pragma warning restore 612, 618
        }
    }
}
